name: Deploy Reactjs application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t gauravraibhatt/reactjs_frontend_stopwatch --build-args APP_ENVIRONMENT_TYPE='production' --build-args API_SERVER_BASE_URL='${{secrets.API_SERVER_BASE_URL}}' .
      - name: Publish Image to Docker hub
        run: docker push gauravraibhatt/reactjs_frontend_stopwatch:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove old docker image
        run: docker rm -f reactjs-container
      - name: Pull Image from docker hub
        run: docker pull gauravraibhatt/reactjs_frontend_stopwatch:latest
      - name: Run docker container
        run: docker run -d -p 80:80 --name reactjs-container gauravraibhatt/reactjs_frontend_stopwatch
        # -p aws:docker(nginx)